ci: add cargo publish workflow for publishing crates (#12)
* ci: add cargo publish workflow for publishing crates

Signed-off-by: Milos Gajdos <milosthegajdos@gmail.com>

---------

Signed-off-by: Milos Gajdos <milosthegajdos@gmail.com>

diff --git a/.github/workflows/ci.yaml b/.github/workflows/ci.yaml
--- a/.github/workflows/ci.yaml
+++ b/.github/workflows/ci.yaml
@@ -2,9 +2,11 @@ name: CI
 
 on:
   push:
-    branches: [ main ]
+    branches: [main]
+    tags:
+      - "*"
   pull_request:
-    branches: [ main ]
+    branches: [main]
 
 env:
   CARGO_TERM_COLOR: always
@@ -13,25 +15,34 @@ jobs:
   ci:
     name: Run CI
     runs-on: ubuntu-latest
+    env:
+      CRATES_TOKEN: ${{ secrets.CRATES_TOKEN }}
 
     steps:
+      - name: check out code
+        uses: actions/checkout@v4
 
-    - name: check out code
-      uses: actions/checkout@v4
+      - name: cargo version and environment
+        id: vars
+        run: |
+          printf "Using cargo at: $(which cargo)\n"
+          printf "cargo version: $(cargo version)\n"
 
-    - name: cargo version and environment
-      id: vars
-      run: |
-        printf "Using cargo at: $(which cargo)\n"
-        printf "cargo version: $(cargo version)\n"
+      - name: setup rust toolchain
+        uses: dtolnay/rust-toolchain@stable
 
-    - name: setup rust toolchain
-      uses: dtolnay/rust-toolchain@stable
+      - name: run build
+        run: |
+          cargo check --verbose
+          cargo build --release --verbose
 
-    - name: run build
-      run: |
-        cargo check --verbose
-        cargo build --release --verbose
+      - name: run tests
+        run: cargo test --verbose
 
-    - name: run tests
-      run: cargo test --verbose
+      - name: publish crate
+        if: startsWith(github.ref, 'refs/tags/')
+        run: |
+          PLAYHTRS_TMP=$(mktemp /tmp/playhtrsXXX.txt) || echo "::error::mktemp error"
+          echo "PLAYHTRS_TMP=$PLAYHTRS_TMP" >> $GITHUB_ENV
+          cargo publish --token $CRATES_TOKEN 2> $PLAYHTRS_TMP
+          cat $PLAYHTRS_TMP
